import { Link, useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { ArrowUpRight, BookOpen, CalendarDays, CheckCircle2, ChevronRight, Flame, Loader2, Sparkles, Target } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Radar, RadarChart, PolarAngleAxis, PolarGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

function scoreStatus(score: number) { return score > 74 ? "Strong" : score > 55 ? "Building" : "Next focus"; }

export default function Dashboard() {
  const [, navigate] = useLocation();
  const overview = trpc.program.overview.useQuery();
  if (overview.isLoading) return <div className="grid min-h-[60vh] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#a5f4c9]" /></div>;
  if (overview.error) return <div className="empty-state"><p>{overview.error.message}</p></div>;
  const data = overview.data!;
  if (!data.profile?.onboardingCompleted || data.profile.onboardingCompleted === "false") { navigate("/onboarding"); return null; }
  const current = data.activeDay;
  const scoreData = [
    { skill: "Clarity", score: data.scores.clarity || data.profile.baselineClarity * 10 },
    { skill: "Concise", score: data.scores.conciseness || data.profile.baselineConciseness * 10 },
    { skill: "Confidence", score: data.scores.confidence || data.profile.baselineConfidence * 10 },
    { skill: "Structure", score: data.scores.structure || data.profile.baselineStructure * 10 },
  ];
  const trend = data.weeklyTrend;
  return <div className="workspace-content"><section className="dashboard-hero"><div><p className="eyebrow">Your practice room</p><h1 className="mt-3 font-display text-4xl tracking-[-0.03em] text-white sm:text-5xl">Make the next conversation count.</h1><p className="mt-4 max-w-xl text-base leading-7 text-[#a5beb6]">Your program is built around one deliberate practice at a time. Today, choose precision over performance.</p></div><div className="hero-orbit"><span className="hero-orbit__number">{data.completionRate}%</span><span className="hero-orbit__label">program complete</span></div></section>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.5fr_.8fr]"><article className="today-card"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-[#a5f4c9]">Today’s practice</p><p className="mt-2 text-sm text-[#9bb4a9]">Day {current} of 28 · approximately 12 minutes</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-white">{current === 28 ? "Mastery showcase" : `Your next articulation lesson`}</h2></div><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#a5f4c9] text-[#09231b]"><Target className="h-5 w-5" /></span></div><p className="mt-4 max-w-xl leading-7 text-[#c8d8d1]">Build a clear message, take one considered response, and use specific coaching to make the next one stronger.</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => navigate(`/lessons/${current}`)} className="premium-button">Start Day {current} <ChevronRight className="ml-1 h-4 w-4" /></Button><Button variant="ghost" onClick={() => navigate("/library")} className="text-[#d9ebe2] hover:bg-white/7 hover:text-white">Browse library</Button></div></article>
      <article className="streak-card"><div className="flex items-center gap-2 text-[#d9ebe2]"><Flame className="h-5 w-5 text-[#f4bc79]" /><span className="font-medium">Practice momentum</span></div><p className="mt-6 font-display text-6xl tracking-[-0.04em] text-white">{data.streak}</p><p className="mt-1 text-sm text-[#9bb4a9]">day current streak</p><div className="mt-7 flex gap-1.5">{Array.from({ length: 7 }, (_, index) => <span key={index} className={`h-2 flex-1 rounded-full ${index < Math.min(data.streak, 7) ? "bg-[#a5f4c9]" : "bg-white/10"}`} />)}</div><p className="mt-3 text-xs leading-5 text-[#9bb4a9]">A consistent cue beats an occasional breakthrough.</p></article></section>
  <section className="mt-5 grid gap-5 lg:grid-cols-2 xl:grid-cols-[.9fr_1.1fr_1.1fr]"><article className="insight-card"><div className="flex items-center justify-between"><div><p className="text-sm text-[#9bb4a9]">Completion</p><p className="mt-2 text-3xl font-semibold text-white">{data.daysCompleted}<span className="text-base font-normal text-[#9bb4a9]"> / 28</span></p></div><CalendarDays className="h-5 w-5 text-[#a5f4c9]" /></div><div className="mt-6 h-2 rounded-full bg-white/8"><div className="h-full rounded-full bg-[#a5f4c9]" style={{ width: `${data.completionRate}%` }} /></div><p className="mt-3 text-xs text-[#9bb4a9]">{data.completionRate}% of the full practice arc.</p></article><article className="insight-card xl:col-span-2"><div className="flex items-center justify-between"><div><p className="text-sm text-[#9bb4a9]">Communication trajectory</p><p className="mt-1 text-lg font-semibold text-white">Your measured signal over time</p></div>{trend.length > 1 && <span className="text-sm font-medium text-[#a5f4c9]">+{Math.max(0, trend.at(-1)!.score - trend[0]!.score)} pts</span>}</div>{trend.length ? <div className="mt-4 h-32"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="trendFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#a5f4c9" stopOpacity={0.38}/><stop offset="100%" stopColor="#a5f4c9" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#ffffff13"/><XAxis dataKey="week" axisLine={false} tickLine={false} tick={{ fill: "#9bb4a9", fontSize: 11 }}/><YAxis hide domain={[0, 100]}/><Tooltip contentStyle={{ background: "#0d211b", border: "1px solid #ffffff20", borderRadius: 12 }} labelStyle={{ color: "#d9ebe2" }}/><Area type="monotone" dataKey="score" stroke="#a5f4c9" strokeWidth={2.5} fill="url(#trendFill)" /></AreaChart></ResponsiveContainer></div> : <p className="mt-7 max-w-sm text-sm leading-6 text-[#9bb4a9]">Submit a first practice to begin your measured communication trajectory.</p>}</article></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="section-card"><div className="flex items-center justify-between"><div><p className="text-sm text-[#9bb4a9]">Skill signal</p><h2 className="mt-1 text-xl font-semibold text-white">Where your message is landing</h2></div><Link href="/progress" className="inline-flex items-center text-sm text-[#a5f4c9] hover:text-white">Full progress <ArrowUpRight className="ml-1 h-4 w-4" /></Link></div><div className="mt-2 grid gap-4 md:grid-cols-[.9fr_1.1fr]"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><RadarChart data={scoreData}><PolarGrid stroke="#ffffff18"/><PolarAngleAxis dataKey="skill" tick={{ fill: "#b2c6be", fontSize: 11 }}/><Radar dataKey="score" stroke="#a5f4c9" fill="#a5f4c9" fillOpacity={0.22}/></RadarChart></ResponsiveContainer></div><div className="my-auto space-y-3">{scoreData.map(item => <div key={item.skill} className="flex items-center justify-between border-b border-white/8 pb-3"><div><p className="font-medium text-white">{item.skill}</p><p className="mt-0.5 text-xs text-[#9bb4a9]">{scoreStatus(item.score)}</p></div><p className="text-lg font-semibold text-[#a5f4c9]">{item.score}</p></div>)}</div></div></article><article className="section-card"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[#f4bc79]"/><p className="text-sm text-[#9bb4a9]">Focus for your next take</p></div><h2 className="mt-3 text-xl font-semibold text-white">Make the opening do more work.</h2><p className="mt-3 leading-7 text-[#b2c6be]">Begin with the conclusion or question that matters most. It gives the listener a reason to stay with the rest of your message.</p><Button onClick={() => navigate(`/lessons/${current}`)} variant="outline" className="mt-6 border-white/15 bg-transparent text-white hover:bg-white/10 hover:text-white">Practice now <BookOpen className="ml-2 h-4 w-4" /></Button></article></section>
  </div>;
}
