export type LessonCategory =
  | "Foundations"
  | "Meetings"
  | "Presence"
  | "Influence"
  | "Leadership"
  | "Career";

export type CurriculumLesson = {
  day: number;
  title: string;
  category: LessonCategory;
  duration: string;
  objective: string;
  reading: string;
  videoTip: string;
  videoSearchQuery: string;
  prompt: string;
};

export const curriculum: CurriculumLesson[] = [
  { day: 1, title: "Confident introductions", category: "Foundations", duration: "12 min", objective: "Create an introduction that sounds grounded, relevant, and easy to remember.", reading: "A concise introduction has three moves: name your role, name the outcome you create, then open a bridge to the other person. Replace your résumé recital with one clear sentence that gives people a reason to continue the conversation.", videoTip: "Watch how a speaker lands a one-sentence professional introduction without rushing the final phrase.", videoSearchQuery: "professional introduction executive communication", prompt: "Record or write a 30-second introduction for a new cross-functional colleague. Include your role, the value you create, and one welcoming question." },
  { day: 2, title: "Clear meeting contributions", category: "Meetings", duration: "10 min", objective: "Contribute a point that colleagues can understand and act on.", reading: "Before speaking, name the point you want remembered. Then provide only the evidence required to make it credible. A meeting contribution becomes more useful when it finishes with a recommendation, request, or decision.", videoTip: "Observe how a concise update uses a headline before supporting detail.", videoSearchQuery: "clear concise meeting communication", prompt: "Respond to this update: a launch date is at risk because a dependency slipped. Give a 45-second contribution that names the risk, impact, and your recommendation." },
  { day: 3, title: "Explaining complex ideas", category: "Foundations", duration: "14 min", objective: "Translate a complex topic into language a non-specialist can follow.", reading: "Complex ideas become clear when you begin with the decision or consequence, not the mechanism. Use a familiar comparison, define unfamiliar terms once, and then return to the result your listener cares about.", videoTip: "Look for the moment a technical speaker shifts from jargon to a practical analogy.", videoSearchQuery: "explaining complex ideas simply presentation", prompt: "Explain a process from your work to a new executive sponsor in under one minute, without relying on jargon." },
  { day: 4, title: "Persuasive argument structure", category: "Influence", duration: "12 min", objective: "Build recommendations that make the next decision obvious.", reading: "A persuasive argument is not a collection of reasons. It is a path: state the recommendation, establish the problem, offer the proof, and specify the next action. The structure keeps listeners from deciding what you meant.", videoTip: "Study a recommendation that leads with the answer and then earns agreement.", videoSearchQuery: "persuasive communication recommendation structure", prompt: "Recommend investing in a customer-retention initiative. Use the sequence: recommendation, reason, evidence, next step." },
  { day: 5, title: "Presentation hooks", category: "Presence", duration: "10 min", objective: "Open a presentation with relevance rather than a generic greeting.", reading: "The strongest opening creates an immediate gap between the audience’s current situation and the result they want. Use a short question, contrast, or situation that makes the topic matter before you name the agenda.", videoTip: "Notice how an effective presenter earns attention before presenting the first slide.", videoSearchQuery: "presentation opening hook executive", prompt: "Write or record a 40-second opening for a presentation proposing a new customer experience strategy." },
  { day: 6, title: "Handling tough questions", category: "Influence", duration: "12 min", objective: "Respond to difficult questions without becoming defensive or vague.", reading: "Pause before you answer. Acknowledge the substance of the question, offer the most direct answer you can, and then name the evidence or next step that supports it. Calm structure signals confidence even when the answer is incomplete.", videoTip: "Watch how a speaker pauses, acknowledges, and then gives a direct answer under pressure.", videoSearchQuery: "handling difficult questions communication", prompt: "Answer: Why should we believe this timeline when the last one slipped? Keep your response under 60 seconds." },
  { day: 7, title: "Constructive feedback", category: "Leadership", duration: "12 min", objective: "Deliver feedback that protects dignity and creates a useful next step.", reading: "Useful feedback is specific, timely, and future-facing. Describe the observable moment, the impact it created, and the behavior that would produce a better outcome next time. Avoid labels that leave the recipient guessing.", videoTip: "Study a feedback conversation that stays precise, calm, and focused on behavior.", videoSearchQuery: "constructive feedback leadership communication", prompt: "Give a teammate feedback after they interrupted a customer twice during a call. Include observation, impact, and a forward-looking request." },
  { day: 8, title: "Active listening for rapport", category: "Meetings", duration: "10 min", objective: "Demonstrate listening in a way that moves the conversation forward.", reading: "Active listening is visible. Reflect the core idea you heard, check the meaning, and ask one question that shows you understand the stakes. This prevents premature solutions and builds trust.", videoTip: "Notice how the listener paraphrases before asking a more useful follow-up question.", videoSearchQuery: "active listening workplace communication", prompt: "A colleague says, 'I am worried that our team is committing to more than we can deliver.' Respond with a reflection and one clarifying question." },
  { day: 9, title: "Polished email communication", category: "Foundations", duration: "10 min", objective: "Write emails that enable fast, accurate action.", reading: "A strong professional email gives the reader context, the message, and the requested action in that order. Put the decision or request near the top, then include details only if they change the reader’s choice.", videoTip: "Review an email walkthrough that turns a long update into a clear decision request.", videoSearchQuery: "executive email communication concise", prompt: "Write an email requesting approval for a two-week extension to a project milestone. Make the decision, rationale, and next step unmistakable." },
  { day: 10, title: "Networking conversation flow", category: "Career", duration: "12 min", objective: "Move from small talk to a meaningful professional exchange.", reading: "Networking works when curiosity replaces performance. Start with the immediate context, ask an open question about the other person’s work, then offer a short relevant connection. Finish by naming a simple reason to continue the conversation.", videoTip: "Watch how a professional conversation moves from an event opener to a substantive question.", videoSearchQuery: "professional networking conversation tips", prompt: "Record a 60-second conversation opener for someone you meet at an industry event. Include an opener, a question, and a natural closing bridge." },
  { day: 11, title: "Vocal presence and tone", category: "Presence", duration: "12 min", objective: "Use pace, emphasis, and pauses to make your message sound deliberate.", reading: "Tone is shaped by contrast. Slow slightly on the most important sentence, allow a pause after the main point, and vary emphasis rather than increasing volume. A measured pace helps listeners trust the message.", videoTip: "Listen for purposeful pauses and emphasis in an executive update.", videoSearchQuery: "vocal presence pace tone executive", prompt: "Record the following message twice: 'We have a clear path forward, and today I need alignment on the first decision.' On the second take, add one intentional pause and two points of emphasis." },
  { day: 12, title: "Body language for authority", category: "Presence", duration: "10 min", objective: "Align physical presence with a calm, credible verbal message.", reading: "Authority is often communicated through stillness. Choose a balanced stance, keep gestures purposeful, and let your face match the seriousness or optimism of your words. Movement should reinforce a point, not release nervous energy.", videoTip: "Observe how a presenter uses stillness and intentional gestures to reinforce key points.", videoSearchQuery: "executive presence body language", prompt: "Write a short plan for the posture, eye contact, gestures, and pace you will use when delivering a high-stakes update." },
  { day: 13, title: "Leading team discussions", category: "Leadership", duration: "14 min", objective: "Facilitate a discussion toward clarity, inclusion, and a decision.", reading: "A strong facilitator makes the purpose explicit, invites the perspectives needed for a decision, and summarizes before moving on. You do not need to supply every answer; you need to make the group’s thinking visible.", videoTip: "Watch a facilitator frame a decision, invite input, and close with a crisp summary.", videoSearchQuery: "facilitation leadership meeting discussion", prompt: "Open a 15-minute team discussion about competing priorities. State the purpose, invite two perspectives, and explain how the decision will be made." },
  { day: 14, title: "Negotiation phrasing", category: "Influence", duration: "12 min", objective: "Make requests and trade-offs clear while keeping the relationship intact.", reading: "Negotiation language works best when it is direct and conditional. Name the interest behind your request, offer a specific option, and use 'if–then' phrasing to make trade-offs visible. Replace ultimatums with well-defined choices.", videoTip: "Listen for how an effective negotiator frames options without creating unnecessary friction.", videoSearchQuery: "negotiation communication phrasing", prompt: "Negotiate a deadline with a partner team. You need more time, but you can offer an earlier review checkpoint in return." },
  { day: 15, title: "Storytelling for impact", category: "Leadership", duration: "14 min", objective: "Use a concise story to make a business insight memorable.", reading: "Business stories need a real tension, not a dramatic performance. Set the context, name the challenge, show the decision or action, and end with the lesson. One specific moment is more persuasive than a series of general claims.", videoTip: "Notice how a brief workplace story uses one moment to reveal a larger lesson.", videoSearchQuery: "business storytelling leadership", prompt: "Tell a 90-second story about a time your team learned something important from a setback. End with the lesson you would apply now." },
  { day: 16, title: "Impromptu speaking mastery", category: "Presence", duration: "12 min", objective: "Organize an answer quickly when you have little preparation time.", reading: "When speaking off the cuff, use a simple frame: answer, reason, example, close. This prevents you from searching for the perfect sentence while the listener waits. A clear structure is more valuable than an exhaustive answer.", videoTip: "Watch an impromptu answer use a simple structure rather than a long preamble.", videoSearchQuery: "impromptu speaking structure", prompt: "Answer this question in 60 seconds: What is one change that would make our team more effective? Use answer, reason, example, close." },
  { day: 17, title: "Interview response clarity", category: "Career", duration: "14 min", objective: "Answer interview questions with a clear narrative and relevant evidence.", reading: "Interview answers are strongest when they give the listener a result quickly and then show how you produced it. Use situation, action, and result, but spend most of your time on the judgment and action that demonstrate your strengths.", videoTip: "Study an interview answer that reaches the result quickly and then proves it with action.", videoSearchQuery: "interview response STAR method communication", prompt: "Answer: Tell me about a time you influenced a decision without formal authority. Keep the answer to two minutes." },
  { day: 18, title: "Conflict resolution dialogue", category: "Leadership", duration: "14 min", objective: "Address disagreement directly without escalating the relationship.", reading: "Conflict conversations improve when you separate intent from impact. Start with the shared outcome, describe the specific issue without accusation, ask for the other perspective, and propose a path forward. The goal is clarity, not victory.", videoTip: "Observe how a difficult conversation begins with shared purpose before naming the point of disagreement.", videoSearchQuery: "conflict resolution workplace communication", prompt: "Open a conversation with a peer whose late decisions are creating rework for your team. State the shared goal, impact, and question you want to explore." },
  { day: 19, title: "Executive summaries", category: "Leadership", duration: "12 min", objective: "Deliver an update that senior stakeholders can absorb quickly.", reading: "An executive summary starts with the decision, status, or risk—not a chronological recap. Use a three-part shape: headline, proof, ask. The summary should make it clear what leaders need to know and what they need to do.", videoTip: "Look for the way an executive update makes the requested decision explicit in its first sentence.", videoSearchQuery: "executive summary communication update", prompt: "Deliver a 60-second executive update on a project that is on track but has one emerging customer risk. End with a specific request." },
  { day: 20, title: "Decision-making language", category: "Influence", duration: "10 min", objective: "Use language that turns discussion into an accountable decision.", reading: "Teams need to know whether they are exploring, recommending, or deciding. Name the decision owner, criteria, and timing. At the close, repeat what was decided, what remains open, and who owns the next action.", videoTip: "Watch how a meeting leader distinguishes exploration from a final decision.", videoSearchQuery: "decision making meeting language", prompt: "Close a discussion about choosing between two vendors. State the decision, the rationale, the owner, and the next action." },
  { day: 21, title: "Strategic reframing", category: "Influence", duration: "12 min", objective: "Shift a stuck conversation toward the underlying strategic choice.", reading: "Reframing is the skill of changing the question without avoiding it. Move from positions to shared outcomes, constraints, or trade-offs. A useful reframe gives the group a more productive problem to solve.", videoTip: "Listen for the moment a speaker turns a narrow disagreement into a larger strategic question.", videoSearchQuery: "strategic reframing communication", prompt: "Your group is debating which feature to build first. Reframe the conversation around the customer outcome and decision criteria." },
  { day: 22, title: "Influencing without authority", category: "Influence", duration: "14 min", objective: "Earn commitment from stakeholders you do not manage.", reading: "Influence without authority depends on relevance and reciprocity. Understand the other person’s priorities, make the shared benefit concrete, and reduce the effort required to say yes. Pressure is rarely as effective as a well-framed mutual gain.", videoTip: "Watch a stakeholder ask that connects a recommendation to the other party’s stated priorities.", videoSearchQuery: "influencing without authority communication", prompt: "Ask a busy peer team to prioritize a shared project. Connect your request to their goals and propose a low-friction next step." },
  { day: 23, title: "Running a difficult update", category: "Leadership", duration: "14 min", objective: "Communicate disappointing news with ownership and clarity.", reading: "Difficult updates require directness, not optimism without evidence. State what happened, the impact, what you own, and how you will respond. Avoid burying the news in context; clear ownership builds confidence.", videoTip: "Observe how a leader states bad news directly, then provides an accountable recovery plan.", videoSearchQuery: "delivering bad news leadership communication", prompt: "Share an update that a customer commitment will be missed. Explain the impact, ownership, recovery plan, and when the next update will occur." },
  { day: 24, title: "Communicating change", category: "Leadership", duration: "12 min", objective: "Explain change in a way that provides direction and psychological safety.", reading: "People need more than an announcement. Explain why the change is happening, what will be different, what will stay stable, and where they can raise concerns. Speak to both the business reason and the human transition.", videoTip: "Watch a change announcement that balances clarity about the reason with practical support for people affected.", videoSearchQuery: "communicating organizational change leadership", prompt: "Announce a change to your team’s workflow. Explain why, what changes now, what remains the same, and how the team can get support." },
  { day: 25, title: "Client advisory conversations", category: "Meetings", duration: "14 min", objective: "Lead a client conversation with insight rather than a product pitch.", reading: "Advisory conversations begin with the client’s situation. Offer an observation that helps them see a meaningful risk or opportunity, then ask a question that invites them to explore it with you. Useful insight earns the right to recommend.", videoTip: "Notice how an advisor leads with the customer’s context before offering a solution.", videoSearchQuery: "consultative client conversation communication", prompt: "Open a conversation with a client whose growth has slowed. Share one relevant observation, ask a diagnostic question, and suggest a next conversation." },
  { day: 26, title: "Board-level communication", category: "Leadership", duration: "14 min", objective: "Deliver strategic information at the right altitude for governing stakeholders.", reading: "Board-level communication is selective and forward-looking. Focus on material outcomes, risks, choices, and decisions rather than operating detail. Anticipate the questions a governing audience must answer and address them before they ask.", videoTip: "Study how a board-style update separates strategic decisions from operational detail.", videoSearchQuery: "board presentation executive communication", prompt: "Provide a 90-second board update on a strategic initiative. Include status, the key risk, and the decision you need." },
  { day: 27, title: "Personal communication charter", category: "Career", duration: "12 min", objective: "Define the communication behaviors you want colleagues to experience consistently.", reading: "A communication charter turns aspiration into observable practice. Name the qualities you want to be known for, the situations where they matter most, and two or three behaviors that make them visible. Use it as a filter before high-stakes interactions.", videoTip: "Watch how a professional translates values such as clarity and confidence into repeatable communication behaviors.", videoSearchQuery: "personal leadership communication style", prompt: "Draft a short communication charter: the three qualities you want to be known for and one behavior that demonstrates each quality." },
  { day: 28, title: "Mastery showcase", category: "Career", duration: "18 min", objective: "Apply the program’s core skills in one complete, high-stakes message.", reading: "Mastery is not a perfect performance; it is deliberate choice under pressure. Build a message with a clear opening, a structured argument, confident pacing, and a specific close. Compare the result with your baseline to identify your next practice focus.", videoTip: "Review a complete executive message and notice how the opening, evidence, delivery, and close reinforce one another.", videoSearchQuery: "executive communication presentation mastery", prompt: "Deliver a two-minute message proposing a meaningful change at work. Use a hook, recommendation, proof, acknowledgement of one concern, and a direct close." },
];

export const bonusModules = [
  { id: "b1", title: "The five-minute briefing", category: "Leadership", duration: "20 min", summary: "Build a concise spoken briefing for an executive audience." },
  { id: "b2", title: "Global communication nuance", category: "Meetings", duration: "18 min", summary: "Adapt clarity, directness, and context across working cultures." },
  { id: "b3", title: "Camera-ready communication", category: "Presence", duration: "16 min", summary: "Lead more effective virtual meetings and video presentations." },
  { id: "b4", title: "High-stakes Q&A", category: "Influence", duration: "22 min", summary: "Prepare for ambiguity, challenge, and follow-up questions." },
] as const;
